### ISSUE TITLE
2k支持

### ISSUE THREAD

**Issue by GuiXie-Null** [moonlessdark/JiuYinDance#1]

**Comment by moonlessdark** [comment]
由于我采用的是坐标切图，相同分辨率在不同缩放下，坐标点会发生变化。
在我解决找到多显示器下的获取游戏窗口所在的缩放分辨率这个问题前我可能没有太多时间来处理2K分辨率了。
目前只能获取到主显示器的缩放，但副屏的获取不到。
或者您可以自行根据您的分辨率进行坐标点重绘。文件路径为：/common/tools/pic_tools/picCoordinate.py。请根据opecv的切图方式进行找图。

**Comment by moonlessdark** [comment]
我更新了一个大图找小图的版本(v0.0.8.1)，您可以试试，理论上能支持大部分的分辨率。
具体效果请自行测试。
