### ISSUE TITLE
启动环境

### ISSUE THREAD

**Issue by LonnieHwang** [moonlessdark/JiuYinDance#3]
您好，请问是需要python32位环境吗？

**Comment by moonlessdark** [comment]
啊你好，我是用64位写的，32位的话你需要修改一下调用32位的dll文件发自我的手机-------- 原始邮件 --------发件人： LonnieHwang ***@***.***>日期： 2023年12月20日周三 17:45收件人： moonlessdark/JiuYinDance ***@***.***>抄送： Subscribed ***@***.***>主    题： [moonlessdark/JiuYinDance] 启动环境 (Issue #3)
您好，请问是需要python32位环境吗？

**Comment by LonnieHwang** [comment]
好的，感谢。

**Comment by LonnieHwang** [comment]
您好，请问是python那个版本呀，好多依赖库安装不上，我8、9、11都试了。方便留个联系方式吗，
***@***.***。


Lonnie&nbsp;Hwang
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "moonlessdark/JiuYinDance"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月20日(星期三) 晚上6:46
***@***.***&gt;;
抄送:&nbsp;"Lonnie ***@***.******@***.***&gt;;
主题:&nbsp;Re: [moonlessdark/JiuYinDance] 启动环境 (Issue #3)





 啊你好，我是用64位写的，32位的话你需要修改一下调用32位的dll文件发自我的手机-------- 原始邮件 --------发件人： LonnieHwang ***@***.***&gt;日期： 2023年12月20日周三 17:45收件人： moonlessdark/JiuYinDance ***@***.***&gt;抄送： Subscribed ***@***.***&gt;主    题： [moonlessdark/JiuYinDance] 启动环境 (Issue #3) 
 您好，请问是需要python32位环境吗？

**Comment by LonnieHwang** [comment]
q抠：396437133
