### ISSUE TITLE
大佬 现在用什么可以自动操作游戏

### ISSUE THREAD

**Issue by 0Zarathustra0** [moonlessdark/JiuYinDance#5]

**Comment by moonlessdark** [comment]
我也不知道啊，毕竟我不是专门写游戏脚本的，对这方面没啥研究～

**Comment by 0Zarathustra0** [comment]
我也玩九阴的，你这脚本可以记录鼠标动作不

**Comment by moonlessdark** [comment]
不能啊，我就只是为了团练授业写的，鼠标录制的话，你可以看看罗技的鼠标宏录制是否满足你的需求。
如果你有更多的需求的话，如押镖，种植，采集，自动做任务，可以直接去淘宝买脚本，大约50块钱一个月。

**Comment by 0Zarathustra0** [comment]
也没有那些需求 就是想把换挑战点的流程给自动化。太累人了。
